### ISSUE TITLE
JSON format for questions and definitions

### ISSUE THREAD

**Issue by tb-dhk** [HCI-Science-Project/Discord-Bot#5]
upon receiving a new qn in the json (which should be coming from the teacher portal), make an api to add it to the database 

according to @UnidentifiedX, the qn format should be:

```
{
  category: "category"
  question: "question",
  options: ["1", "2", "3", "4"],
  answer: 2,
  explanation: "explanation"
}
```

**Comment by UnidentifiedX** [comment]
Standardised JSON format for questions:
```json
{
  "category": "category",
  "question": "question",
  "option1": "option",
  "option2": "option",
  "option3": "option",
  "option4": "option",
  "answer": 2,
  "explanation": "explanation"
}
```

Standardised JSON format for definitions
```json
"proton": {
  "aliases": [],
  "definition": "A subatomic particle with a relative charge of 1+., found in the nucleus of an atom. Its relative mass is 1."
}
```

Updated as of 15th March 2022

**Comment by DET171** [comment]
Scratch 
```json
"proton": {
  "aliases": [],
  "definition": "A subatomic particle with a relative charge of 1+., found in the nucleus of an atom. Its relative mass is 1."
}
```
Has been updated to 
```json
{
  "item": "adenosine triphosphate",
  "definition": "A compound containing the amino acid adenosine and the phosphate group triphosphate.",
  "aliases": ["atp"]
}
```
to enable fuzzy search (the db will be an array of the definition objects).

Updated as of 20th March 2022

**Comment by DET171** [comment]
Also uh
> upon receiving a new qn in the json (which should be coming from the teacher portal), make an api to add it to the database

I think the teacher's portal will add it straight to the db and make a command for the bot to fetch the qns from the db and refresh its qns list.

**Comment by DET171** [comment]
Um I wrote a new one to make it clearer and in one place without having to scroll down
